language: node_js
node_js:
  - "11"
dist: trusty
sudo: false

cache:
  directories:
    - node_modules

install:
  - npm install

jobs:
  include:
    - stage: test
      name: 'Test'
      script:
        - npm run chk:data
        - npm run prettier
    - stage: build
      name: 'Build website'
      script:
        - npm run build
    - stage: deploy
      name: 'deploy to repository'
      if: branch = master
      env:
        - USER="claviers"
        - EMAIL="vince.legoff@gmail.com"
        - REPO="claviers.github.io"
        - GH_REPO="github.com/${USER}/${REPO}.git"
      script:
        - MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
        - git clone git://${GH_REPO}
        - mv ./dist/* ${REPO}/
        - cd ${REPO}
        - git remote
        - git config user.email ${EMAIL}
        - git config user.name ${USER}
        - git add .
        - git commit -m ${MESSAGE}
        - git push "https://${GITHUB_TOKEN}@${GH_REPO}" master > /dev/null 2>&1
